replicaCount: 1

image:
  repository: ghcr.io/krateoplatformops-workshop/nodejs-1
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000
